### PR TITLE
Building Linux AppImage

### PR DESCRIPTION
**Pull request by denisstrizhkin**

### CODE REVIEW

**Comment by denisstrizhkin** [comment]
For now I am coping res folder into an AppImage but maybe its better to allow it access into a current folder or something. At the very least you can successfully patch an iso.

**Comment by denisstrizhkin** [comment]
I sorted out the res folder location problem by relying on `ARGV0` environmental variable provided by AppImage runtime. So now it basically works completely identical to windows version. If you put this AppImage into FUComplete directory it would work as expected.

**Comment by denisstrizhkin** [comment]
image

**Comment by Hairo** [comment]
Is there any reason to not inlcude xdelta and [SED-PC](https://github.com/BrianBTB/SED-PC) in the appimage? SED-PC is needed for custom quests.

**Comment by denisstrizhkin** [comment]
I haven't tested custom quests yet, so I didn't package sed-pc. The idea was to get most functionality working and get it running. As for xdelta3 it is really common and is available on all distros so in my head I thought a system one can be used.

**Comment by Hairo** [comment]
Well, the whole point of appimage is to have a single file you can run without installing dependencies so having to install xdelta kinda defeats the purpose.

**Comment by denisstrizhkin** [comment]
I see. Will look into putting both in.

**Comment by denisstrizhkin** [comment]
Done

**Comment by Hairo** [comment]
Thank you, tested it and it seems to be working as expected.

**Pull request merged**
